In [1]:
import pandas as pd
import json

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/avnyadav/sensor-fault-detection/main/aps_failure_training_set1.csv")

In [3]:
df.sample(5)

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
5482,neg,20,2,48,20,0,0,0,0,0,...,162,52,58,26,28,4,0,0,0,0
29025,neg,206,na,10,8,0,0,0,0,0,...,1252,232,538,486,1594,3858,0,0,0,0
6774,neg,52452,na,2130706432,186,0,0,0,0,0,...,293976,129112,282232,462952,487498,308754,320854,0,0,0
19414,neg,9170,na,0,na,0,0,0,0,0,...,117134,27344,72836,165380,66,0,0,0,0,0
9058,neg,121400,na,2252,1754,0,0,0,0,0,...,1082608,548460,1021876,867286,677116,452872,776134,46670,0,0

In [8]:
list(json.loads(df.T.to_json()).values())

Output hidden; open in https://colab.research.google.com to view.

In [12]:
df.to_json("APS.json")